# Generated by Django 5.2.14 on 2026-05-19 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('idea_name', models.CharField(max_length=200)),
                ('idea_description', models.TextField()),
                ('target_market', models.CharField(max_length=300)),
                ('problem_solved', models.TextField()),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('build_now', 'Build Now'), ('strong_foundation', 'Strong Foundation'), ('refine_first', 'Refine First'), ('validate_harder', 'Validate Harder'), ('wrong_market', 'Wrong Market')], max_length=30)),
                ('headline', models.CharField(blank=True, max_length=400)),
                ('basic_analysis', models.TextField(blank=True)),
                ('deep_data', models.JSONField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paystack_ref', models.CharField(blank=True, db_index=True, max_length=100)),
                ('analysis_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Idea Submission',
                'verbose_name_plural': 'Idea Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
