# Generated by Django 5.2.14 on 2026-05-17 21:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default='High-conviction technical reports and DX intelligence from the studio.')),
                ('subscription_pitch', models.CharField(blank=True, default='Full reports for Insights members — $0.99/mo.', max_length=200)),
            ],
            options={
                'verbose_name': 'Insights index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InsightsPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(choices=[('architecture', 'Architecture'), ('ai', 'AI & ML'), ('dx', 'Developer Experience'), ('infrastructure', 'Infrastructure'), ('product', 'Product Engineering')], default='architecture', max_length=40)),
                ('summary', models.TextField(blank=True, help_text='Short excerpt shown on the index and to non-members.')),
                ('estimated_read_minutes', models.PositiveSmallIntegerField(default=5)),
                ('is_premium', models.BooleanField(default=True, help_text='If checked, non-members see only the summary and a paywall.')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('pullquote', 3), ('premium_section', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ul', 'ol', 'link', 'h2', 'h3']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {'icon': 'openquote'}), 4: ('wagtail.blocks.StructBlock', [[('content', 1)]], {})})),
            ],
            options={
                'verbose_name': 'Insights post',
                'verbose_name_plural': 'Insights posts',
            },
            bases=('wagtailcore.page',),
        ),
    ]
