# Generated by Django 5.2.14 on 2026-05-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightsindexpage',
            name='subscription_pitch',
            field=models.CharField(blank=True, default='Full reports for Insights members — KES 499 / USD 4.99 per month.', max_length=200),
        ),
    ]
