version: "3.9"

services:
  db:
    image: postgres:14-alpine
    container_name: listmonk_db
    restart: always
    environment:
      - POSTGRES_USER=listmonk
      - POSTGRES_PASSWORD=listmonk
      - POSTGRES_DB=listmonk
    volumes:
      - listmonk_data:/var/lib/postgresql/data

  app:
    image: listmonk/listmonk:latest
    container_name: listmonk_app
    restart: always
    ports:
      - "9000:9000"
    environment:
      - LISTMONK_db__host=db
      - LISTMONK_db__user=listmonk
      - LISTMONK_db__password=listmonk
      - LISTMONK_db__database=listmonk
      - LISTMONK_db__port=5432
      - LISTMONK_app__address=0.0.0.0:9000
    volumes:
      - ./listmonk/config.toml:/listmonk/config.toml
    depends_on:
      - db

volumes:
  listmonk_data:
