# Generated by Django 5.2.14 on 2026-05-18 09:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('client_name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('outcome_tag', models.CharField(choices=[('payment', 'Payment integration'), ('ai', 'AI / Automation'), ('platform', 'Platform build'), ('infra', 'Infrastructure'), ('mobile', 'Mobile-first'), ('data', 'Data & Analytics')], default='platform', max_length=30)),
                ('summary', models.TextField()),
                ('challenge', wagtail.fields.RichTextField(blank=True)),
                ('solution', wagtail.fields.RichTextField(blank=True)),
                ('results', wagtail.fields.RichTextField(blank=True)),
                ('stack', models.CharField(blank=True, help_text='Comma-separated stack items', max_length=300)),
                ('timeline', models.CharField(blank=True, max_length=60)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Case study',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SolutionsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default='Selected work from the studio.')),
            ],
            options={
                'verbose_name': 'Solutions index',
            },
            bases=('wagtailcore.page',),
        ),
    ]
