# Generated by Django 5.2.14 on 2026-05-18 10:11

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_casestudypage_solutionsindexpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
