# Generated by Django 5.2.14 on 2026-05-19 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(db_index=True, max_length=30)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('is_escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_message_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=3)),
                ('body', models.TextField()),
                ('is_escalation_trigger', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal reference name', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('business_description', models.TextField(help_text='2–4 sentences: what the business does, who it serves, its tone')),
                ('mpesa_paybill', models.CharField(blank=True, max_length=30)),
                ('mpesa_account', models.CharField(blank=True, max_length=100)),
                ('whatsapp_phone_number_id', models.CharField(help_text='Phone Number ID from Meta Business Manager (not the phone number itself)', max_length=100, unique=True)),
                ('welcome_message', models.TextField(default='Hello! Welcome. How can I help you today?', help_text='Sent to new contacts on their first message')),
                ('fallback_message', models.TextField(default="I'm having trouble right now. Please try again in a moment or contact us directly.", help_text='Sent when AI or API call fails')),
                ('system_prompt_addon', models.TextField(blank=True, help_text='Extra instructions appended to the base system prompt (product rules, tone, prohibited topics)')),
                ('escalation_phone', models.CharField(blank=True, help_text='WhatsApp number to notify on escalation (international format, e.g. 254712345678)', max_length=30)),
                ('escalation_message_template', models.TextField(default='⚠️ Escalation from {business_name}\nCustomer: {customer_phone}\nMessage: {last_message}')),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='JSON: {"mon":"08:00-18:00","sat":"09:00-14:00","sun":"closed"}')),
                ('outside_hours_message', models.TextField(blank=True, help_text='Message sent when a customer contacts outside business hours. Leave blank to always respond.')),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('plan', models.CharField(choices=[('starter', 'Starter — up to 500 conversations/mo'), ('growth', 'Growth — up to 2,000 conversations/mo'), ('business', 'Business — unlimited')], default='starter', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, help_text="CES platform user who manages this tenant's dashboard", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text='Optional grouping (e.g. Pricing, Hours, Returns)', max_length=100)),
                ('question', models.TextField(help_text='The question or topic trigger')),
                ('answer', models.TextField(help_text='The answer the agent should give')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='agents.tenant')),
            ],
            options={
                'verbose_name': 'Knowledge Entry',
                'verbose_name_plural': 'Knowledge Entries',
                'ordering': ['category', 'question'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agents.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('tenant', 'customer_phone')},
        ),
    ]
